download_and_prepare_model:
	echo "Download pretrained model..."
	./googleDriveDownload.sh 1JrQ6HRqDZQZneaXhytvzVmLl3Wa62HK_ models/cat_vs_dog.zip
	echo "Install unzip package..."
	apt-get install unzip
	echo "Unzip pretrained model..."
	echo "Finished!"

